/* ============================================================
   Embedded fallback data for Your Japanese Knife.
   Lets the page run straight from file:// (no server needed).
   Keep this in sync with knives.json. app.js prefers fetch()
   and falls back to window.KNIFE_DATA when fetch is blocked.
   ============================================================ */
window.KNIFE_DATA = {
  "knives": [
    {
      "id": "gyuto",
      "name": "Gyuto",
      "kanji": "牛刀",
      "translation": "Cow Sword",
      "role": "The All-Rounder",
      "rarity": "common",
      "purpose": "The Japanese take on the Western chef's knife. A versatile do-everything blade for meat, fish, and vegetables.",
      "bladeLength": "210–270 mm",
      "profile": "Curved belly for rock-chopping, pointed tip for detail work.",
      "bestFor": ["Slicing meat", "Dicing vegetables", "General prep", "Rock chopping"],
      "avoid": ["Cleaving through bone", "Peeling small produce"],
      "difficulty": 1,
      "edge": "Double bevel",
      "stats": { "versatility": 10, "precision": 7, "power": 6, "agility": 7 },
      "tip": "If you buy only one Japanese knife, make it a Gyuto.",
      "emoji": "🔪"
    },
    {
      "id": "santoku",
      "name": "Santoku",
      "kanji": "三徳",
      "translation": "Three Virtues",
      "role": "The Home Hero",
      "rarity": "common",
      "purpose": "Named for its mastery of three tasks: meat, fish, and vegetables. Shorter and flatter than a Gyuto.",
      "bladeLength": "165–180 mm",
      "profile": "Flat edge with a sheep's-foot tip, made for push-cutting.",
      "bestFor": ["Push cutting", "Everyday home cooking", "Thin slicing", "Chopping herbs"],
      "avoid": ["Rock chopping", "Large roasts"],
      "difficulty": 1,
      "edge": "Double bevel",
      "stats": { "versatility": 9, "precision": 7, "power": 5, "agility": 8 },
      "tip": "The flat profile rewards a clean up-and-down chopping motion.",
      "emoji": "🥕"
    },
    {
      "id": "nakiri",
      "name": "Nakiri",
      "kanji": "菜切",
      "translation": "Vegetable Cutter",
      "role": "The Garden Specialist",
      "rarity": "uncommon",
      "purpose": "A straight, rectangular blade built purely for vegetables. Cuts clean all the way through in one motion.",
      "bladeLength": "165–180 mm",
      "profile": "Flat, tall, and square — no rocking, just clean drops.",
      "bestFor": ["Slicing cabbage", "Paper-thin cuts", "Batonnet & julienne", "Katsuramuki peeling"],
      "avoid": ["Meat with bones", "Detailed tip work"],
      "difficulty": 2,
      "edge": "Double bevel",
      "stats": { "versatility": 5, "precision": 9, "power": 6, "agility": 6 },
      "tip": "The tall blade doubles as a bench scraper to move your cuts.",
      "emoji": "🥬"
    },
    {
      "id": "petty",
      "name": "Petty",
      "kanji": "ペティ",
      "translation": "Petite",
      "role": "The Nimble Sidekick",
      "rarity": "common",
      "purpose": "A small utility knife for tasks too delicate for a big blade and too big for a paring knife.",
      "bladeLength": "120–150 mm",
      "profile": "Slim, pointed, and lightweight for in-hand work.",
      "bestFor": ["Peeling", "Trimming fat", "Slicing fruit", "Detail work"],
      "avoid": ["Heavy chopping", "Dense vegetables"],
      "difficulty": 1,
      "edge": "Double bevel",
      "stats": { "versatility": 7, "precision": 9, "power": 3, "agility": 10 },
      "tip": "Keep one next to your main knife as a constant companion.",
      "emoji": "🍓"
    },
    {
      "id": "sujihiki",
      "name": "Sujihiki",
      "kanji": "筋引",
      "translation": "Sinew Slicer",
      "role": "The Long Blade",
      "rarity": "rare",
      "purpose": "A long, slender slicer for carving proteins into clean, single-stroke slices.",
      "bladeLength": "240–300 mm",
      "profile": "Narrow and long to slice without sawing.",
      "bestFor": ["Carving roasts", "Slicing sashimi-style", "Portioning fish", "Brisket"],
      "avoid": ["Chopping", "Vegetable prep"],
      "difficulty": 2,
      "edge": "Double bevel",
      "stats": { "versatility": 4, "precision": 10, "power": 5, "agility": 6 },
      "tip": "Let the length do the work — pull through in one smooth draw.",
      "emoji": "🥩"
    },
    {
      "id": "yanagiba",
      "name": "Yanagiba",
      "kanji": "柳刃",
      "translation": "Willow Blade",
      "role": "The Sushi Master",
      "rarity": "epic",
      "purpose": "A single-bevel slicer designed for pristine sashimi and sushi cuts with a mirror-clean surface.",
      "bladeLength": "270–330 mm",
      "profile": "Long, single-bevel, and razor-keen for one-draw cuts.",
      "bestFor": ["Sashimi", "Sushi slicing", "Raw fish", "Clean single strokes"],
      "avoid": ["Left-hand use (traditionally right-handed)", "Chopping"],
      "difficulty": 4,
      "edge": "Single bevel",
      "stats": { "versatility": 3, "precision": 10, "power": 4, "agility": 5 },
      "tip": "The single bevel demands practice — but delivers glass-smooth slices.",
      "emoji": "🍣"
    },
    {
      "id": "deba",
      "name": "Deba",
      "kanji": "出刃",
      "translation": "Pointed Carver",
      "role": "The Fish Butcher",
      "rarity": "rare",
      "purpose": "A thick, heavy single-bevel knife for breaking down whole fish, including light bones.",
      "bladeLength": "150–210 mm",
      "profile": "Heavy spine and single bevel for power and control.",
      "bestFor": ["Filleting fish", "Cutting through fish heads", "Light bones", "Butchery"],
      "avoid": ["Vegetable slicing", "Delicate garnish work"],
      "difficulty": 3,
      "edge": "Single bevel",
      "stats": { "versatility": 4, "precision": 6, "power": 9, "agility": 4 },
      "tip": "Use the heel for bone, the tip for delicate filleting.",
      "emoji": "🐟"
    },
    {
      "id": "honesuki",
      "name": "Honesuki",
      "kanji": "骨スキ",
      "translation": "Bone Separator",
      "role": "The Poultry Pro",
      "rarity": "uncommon",
      "purpose": "A triangular boning knife built to break down poultry with precision around joints.",
      "bladeLength": "145–150 mm",
      "profile": "Rigid, pointed, and triangular for tight joint work.",
      "bestFor": ["Breaking down chicken", "Boning", "Joint separation", "Butchery"],
      "avoid": ["Slicing vegetables", "Long carving strokes"],
      "difficulty": 3,
      "edge": "Double bevel (asymmetric)",
      "stats": { "versatility": 5, "precision": 8, "power": 7, "agility": 6 },
      "tip": "The stiff tip pops joints apart without cutting bone.",
      "emoji": "🍗"
    },
    {
      "id": "kiritsuke",
      "name": "Kiritsuke",
      "kanji": "切付",
      "translation": "Slit Maker",
      "role": "The Chef's Crown",
      "rarity": "epic",
      "purpose": "A hybrid of Gyuto and Yanagiba with an angular reverse-tanto tip — traditionally the mark of a head chef.",
      "bladeLength": "210–270 mm",
      "profile": "Straight edge with a dramatic angled tip.",
      "bestFor": ["Slicing", "Vegetable prep", "Showpiece cutting", "Versatile pro use"],
      "avoid": ["Beginners", "Rock chopping"],
      "difficulty": 4,
      "edge": "Double or single bevel",
      "stats": { "versatility": 8, "precision": 9, "power": 6, "agility": 6 },
      "tip": "A demanding blade earned through skill — handle with respect.",
      "emoji": "👑"
    },
    {
      "id": "bunka",
      "name": "Bunka",
      "kanji": "文化",
      "translation": "Culture",
      "role": "The Modern Maverick",
      "rarity": "rare",
      "purpose": "A stylish all-rounder like the Santoku but with a sharp reverse-tanto tip for extra point control.",
      "bladeLength": "165–180 mm",
      "profile": "Flat edge with a striking angular K-tip.",
      "bestFor": ["Everyday prep", "Precise tip work", "Vegetables", "Boneless proteins"],
      "avoid": ["Bones", "Rock chopping"],
      "difficulty": 2,
      "edge": "Double bevel",
      "stats": { "versatility": 8, "precision": 8, "power": 5, "agility": 8 },
      "tip": "The pointed tip makes scoring and precise cuts effortless.",
      "emoji": "🎌"
    }
  ],
  "stones": [
    {
      "id": "coarse",
      "name": "Coarse",
      "kanji": "荒砥",
      "translation": "Rough Stone",
      "role": "The Repairer",
      "grit": "#120–#400",
      "tier": "Coarse",
      "stage": "Repair & reprofiling",
      "soak": "Soak 10–15 min",
      "purpose": "The heavy-metal remover. A coarse stone cuts fast to fix chips, reset a broken bevel, or thin a blade behind the edge. It leaves a toothy, aggressive edge that always needs refining afterward.",
      "bestFor": ["Repairing chips", "Reprofiling a bevel", "Thinning the blade", "Reviving very dull knives"],
      "avoid": ["Everyday touch-ups", "Finishing an edge", "Polishing", "Delicate single-bevels"],
      "fineness": 1,
      "stats": { "speed": 10, "refinement": 2, "versatility": 3, "gentleness": 1 },
      "tip": "Only reach for a coarse stone when there is real damage — it removes a lot of steel.",
      "emoji": "🪨"
    },
    {
      "id": "medium",
      "name": "Medium",
      "kanji": "中砥",
      "translation": "Middle Stone",
      "role": "The All-Rounder",
      "grit": "#800–#2000",
      "tier": "Medium",
      "stage": "Main sharpening",
      "soak": "Soak 5–10 min",
      "purpose": "The workhorse of the set. A medium stone does the core sharpening on a dull-but-undamaged knife and sets the edge most cooks rely on. If you own only one whetstone, this is the tier to choose.",
      "bestFor": ["Main sharpening", "Dull, undamaged knives", "All-purpose use", "Your only-one stone"],
      "avoid": ["Fixing deep chips", "Mirror polishing", "Heavy reprofiling", "Thinning the blade"],
      "fineness": 2,
      "stats": { "speed": 7, "refinement": 6, "versatility": 10, "gentleness": 5 },
      "tip": "If you buy only one whetstone, make it around #1000.",
      "emoji": "🧱"
    },
    {
      "id": "fine",
      "name": "Fine",
      "kanji": "仕上砥",
      "translation": "Finishing Stone",
      "role": "The Refiner",
      "grit": "#3000–#5000",
      "tier": "Fine",
      "stage": "Refining & polish",
      "soak": "Splash or short soak",
      "purpose": "The clean-up stone. After the medium grit, a fine stone refines the edge, removes deeper scratches, and adds a light everyday polish for smooth push-cuts. It does not remove much metal.",
      "bestFor": ["Refining after medium", "Removing scratches", "Everyday polish", "Smooth push-cuts"],
      "avoid": ["Setting a new bevel", "Repairing damage", "Fast metal removal", "Fixing chips"],
      "fineness": 3,
      "stats": { "speed": 4, "refinement": 8, "versatility": 6, "gentleness": 7 },
      "tip": "Follow the medium stone with this to clean up and sharpen the edge.",
      "emoji": "🌟"
    },
    {
      "id": "very-fine",
      "name": "Very Fine",
      "kanji": "上仕上",
      "translation": "Super Finishing",
      "role": "The Polisher",
      "grit": "#6000–#8000",
      "tier": "Very Fine",
      "stage": "Finishing keenness",
      "soak": "Splash only",
      "purpose": "The keenness stone. A very fine grit polishes a slicer for extra push-cutting sharpness and removes the burr before you move to a strop. It cuts slowly and is very gentle on steel.",
      "bestFor": ["Extra keenness", "Push-cutting slicers", "Prep before stropping", "Refined edges"],
      "avoid": ["Repair work", "Setting bevels", "Toothy utility edges", "Fast sharpening"],
      "fineness": 4,
      "stats": { "speed": 2, "refinement": 9, "versatility": 4, "gentleness": 9 },
      "tip": "A great final stone right before stropping a razor edge.",
      "emoji": "✨"
    },
    {
      "id": "ultra-fine",
      "name": "Ultra Fine",
      "kanji": "鏡面",
      "translation": "Mirror Face",
      "role": "The Mirror",
      "grit": "#10000+",
      "tier": "Ultra Fine",
      "stage": "Mirror finishing",
      "soak": "Splash only",
      "purpose": "The polishing stone. The final grit before stropping, it produces a mirror finish and the highest possible sharpness — ideal for single-bevel sushi knives. Splash-and-go, never soaked.",
      "bestFor": ["Mirror polish", "Single-bevel sushi knives", "Highest sharpness", "Show finishes"],
      "avoid": ["Repair or reprofiling", "Everyday quick sharpening", "Toothy edges", "A beginner's only stone"],
      "fineness": 5,
      "stats": { "speed": 1, "refinement": 10, "versatility": 3, "gentleness": 10 },
      "tip": "The finishing touch for single-bevel sashimi knives.",
      "emoji": "💎"
    }
  ],
  "quiz": [
    { "scenario": "You need to slice a fresh block of tuna into flawless sashimi.", "answer": "yanagiba", "options": ["yanagiba", "nakiri", "deba", "honesuki"] },
    { "scenario": "You're breaking down a whole chicken around the joints.", "answer": "honesuki", "options": ["honesuki", "petty", "sujihiki", "santoku"] },
    { "scenario": "You want one knife to handle meat, fish, and veg for daily cooking.", "answer": "gyuto", "options": ["gyuto", "yanagiba", "deba", "kiritsuke"] },
    { "scenario": "You have a mountain of cabbage to shred paper-thin.", "answer": "nakiri", "options": ["nakiri", "sujihiki", "honesuki", "deba"] },
    { "scenario": "You need to fillet a whole fish and cut through its head.", "answer": "deba", "options": ["deba", "petty", "nakiri", "gyuto"] },
    { "scenario": "You're carving a large roast into clean, single-stroke slices.", "answer": "sujihiki", "options": ["sujihiki", "santoku", "nakiri", "honesuki"] },
    { "scenario": "You want a small nimble knife to peel and trim fruit in hand.", "answer": "petty", "options": ["petty", "deba", "yanagiba", "kiritsuke"] },
    { "scenario": "You prefer a flat blade for clean up-and-down home chopping.", "answer": "santoku", "options": ["santoku", "sujihiki", "deba", "yanagiba"] },
    { "scenario": "You need to slice a cooked brisket into long, even slices.", "answer": "sujihiki", "options": ["sujihiki", "nakiri", "honesuki", "deba"] },
    { "scenario": "You want a modern all-rounder with a sharp reverse-tanto tip for scoring.", "answer": "bunka", "options": ["bunka", "deba", "yanagiba", "sujihiki"] },
    { "scenario": "A head chef traditionally carries this angular hybrid slicer as a badge of rank.", "answer": "kiritsuke", "options": ["kiritsuke", "petty", "nakiri", "honesuki"] },
    { "scenario": "You want to julienne carrots cleanly with a veg-only blade.", "answer": "nakiri", "options": ["nakiri", "deba", "sujihiki", "yanagiba"] },
    { "scenario": "You need to slice raw salmon cleanly for nigiri.", "answer": "yanagiba", "options": ["yanagiba", "santoku", "honesuki", "nakiri"] },
    { "scenario": "You want to remove a chicken breast neatly from the carcass.", "answer": "honesuki", "options": ["honesuki", "yanagiba", "nakiri", "petty"] },
    { "scenario": "You need to cut through a fish collar and small bones.", "answer": "deba", "options": ["deba", "petty", "sujihiki", "santoku"] },
    { "scenario": "You want to peel an apple comfortably in your hand.", "answer": "petty", "options": ["petty", "deba", "gyuto", "kiritsuke"] },
    { "scenario": "You're dicing onions with a rocking motion on the board.", "answer": "gyuto", "options": ["gyuto", "nakiri", "deba", "yanagiba"] },
    { "scenario": "You want to carve a holiday turkey into tidy slices.", "answer": "sujihiki", "options": ["sujihiki", "nakiri", "honesuki", "deba"] },
    { "scenario": "You want to cut finished sushi rolls into clean pieces.", "answer": "yanagiba", "options": ["yanagiba", "deba", "nakiri", "honesuki"] },
    { "scenario": "A home cook wants one compact, easy Japanese knife for daily prep.", "answer": "santoku", "options": ["santoku", "yanagiba", "deba", "kiritsuke"] },
    { "scenario": "You want to slice cucumber into thin, even ribbons for garnish.", "answer": "nakiri", "options": ["nakiri", "deba", "honesuki", "sujihiki"] },
    { "scenario": "You want the longest blade for single-stroke, double-bevel protein slicing.", "answer": "sujihiki", "options": ["sujihiki", "petty", "nakiri", "santoku"] },
    { "scenario": "You want to trim silverskin and fat off a tenderloin with fine control.", "answer": "petty", "options": ["petty", "deba", "nakiri", "yanagiba"] },
    { "scenario": "You want a stylish home knife but with a pointed K-tip for detail work.", "answer": "bunka", "options": ["bunka", "sujihiki", "deba", "yanagiba"] },
    { "scenario": "You want to make the final, glass-smooth slices on sashimi-grade fish.", "answer": "yanagiba", "options": ["yanagiba", "honesuki", "nakiri", "gyuto"] },
    { "scenario": "You want a versatile do-everything blade with a curved belly for rock-chopping.", "answer": "gyuto", "options": ["gyuto", "nakiri", "deba", "yanagiba"] },
    { "scenario": "Which knife's name means 'Three Virtues'?", "answer": "santoku", "options": ["santoku", "gyuto", "nakiri", "deba"] },
    { "scenario": "Which knife's name translates to 'Cow Sword'?", "answer": "gyuto", "options": ["gyuto", "yanagiba", "petty", "bunka"] },
    { "scenario": "Which knife's name means 'Vegetable Cutter'?", "answer": "nakiri", "options": ["nakiri", "deba", "sujihiki", "honesuki"] },
    { "scenario": "Which knife's name means 'Willow Blade'?", "answer": "yanagiba", "options": ["yanagiba", "kiritsuke", "santoku", "deba"] },
    { "scenario": "Which of these is a traditional single-bevel knife for slicing fish?", "answer": "yanagiba", "options": ["yanagiba", "gyuto", "santoku", "nakiri"] },
    { "scenario": "Which single-bevel knife is thick and heavy for butchering whole fish?", "answer": "deba", "options": ["deba", "petty", "sujihiki", "bunka"] },
    { "scenario": "Which knife is a triangular boning knife made for poultry?", "answer": "honesuki", "options": ["honesuki", "nakiri", "yanagiba", "gyuto"] },
    { "scenario": "Which knife is a tall, rectangular, flat-profiled vegetable blade?", "answer": "nakiri", "options": ["nakiri", "sujihiki", "deba", "petty"] },
    { "scenario": "Which knife is essentially a Santoku with a sharp reverse-tanto tip?", "answer": "bunka", "options": ["bunka", "kiritsuke", "deba", "yanagiba"] },
    { "scenario": "Which knife is a long, slender, double-bevel slicer for proteins?", "answer": "sujihiki", "options": ["sujihiki", "nakiri", "honesuki", "deba"] },
    { "scenario": "If you could buy only one Japanese knife, which is the classic pick?", "answer": "gyuto", "options": ["gyuto", "deba", "yanagiba", "honesuki"] },
    { "scenario": "Which knife is actually DESIGNED to power through fish bones?", "answer": "deba", "options": ["deba", "gyuto", "petty", "sujihiki"] },
    { "scenario": "You want to break down a fish, then a companion blade to slice it into sashimi. Which does the slicing?", "answer": "yanagiba", "options": ["yanagiba", "deba", "honesuki", "nakiri"] },
    { "scenario": "Your knife has a chipped edge that needs repairing. Which whetstone grit?", "answer": "Coarse #120–#400", "options": ["Coarse #120–#400", "Medium #800–#2000", "Fine #3000–#5000", "Ultra Fine #10000+"] },
    { "scenario": "You need to reprofile and set a brand-new bevel on a very dull knife. Which grit?", "answer": "Coarse #120–#400", "options": ["Coarse #120–#400", "Fine #3000–#5000", "Very Fine #6000–#8000", "Ultra Fine #10000+"] },
    { "scenario": "If you own only ONE whetstone, which grit range is the best all-purpose choice?", "answer": "Medium #800–#2000", "options": ["Medium #800–#2000", "Coarse #120–#400", "Very Fine #6000–#8000", "Ultra Fine #10000+"] },
    { "scenario": "Your knife is simply dull but undamaged. Which grit does the main sharpening?", "answer": "Medium #800–#2000", "options": ["Medium #800–#2000", "Coarse #120–#400", "Fine #3000–#5000", "Ultra Fine #10000+"] },
    { "scenario": "After coarse work, which grit refines the edge and removes deep scratches?", "answer": "Fine #3000–#5000", "options": ["Fine #3000–#5000", "Coarse #120–#400", "Medium #800–#2000", "Ultra Fine #10000+"] },
    { "scenario": "Which grit gives a light everyday maintenance polish to a decent edge?", "answer": "Fine #3000–#5000", "options": ["Fine #3000–#5000", "Coarse #120–#400", "Very Fine #6000–#8000", "Medium #800–#2000"] },
    { "scenario": "You want to finish a slicer for extra push-cutting keenness. Which grit?", "answer": "Very Fine #6000–#8000", "options": ["Very Fine #6000–#8000", "Coarse #120–#400", "Medium #800–#2000", "Fine #3000–#5000"] },
    { "scenario": "You want a mirror polish on a single-bevel sushi knife. Which grit?", "answer": "Ultra Fine #10000+", "options": ["Ultra Fine #10000+", "Coarse #120–#400", "Medium #800–#2000", "Fine #3000–#5000"] },
    { "scenario": "A #1000 grit whetstone is generally classified as which tier?", "answer": "Medium #800–#2000", "options": ["Medium #800–#2000", "Coarse #120–#400", "Fine #3000–#5000", "Ultra Fine #10000+"] },
    { "scenario": "A #220 grit whetstone is classified as which tier?", "answer": "Coarse #120–#400", "options": ["Coarse #120–#400", "Medium #800–#2000", "Fine #3000–#5000", "Very Fine #6000–#8000"] },
    { "scenario": "A #6000 grit whetstone is classified as which tier?", "answer": "Very Fine #6000–#8000", "options": ["Very Fine #6000–#8000", "Coarse #120–#400", "Medium #800–#2000", "Fine #3000–#5000"] },
    { "scenario": "A #400 grit whetstone is classified as which tier?", "answer": "Coarse #120–#400", "options": ["Coarse #120–#400", "Medium #800–#2000", "Very Fine #6000–#8000", "Ultra Fine #10000+"] },
    { "scenario": "A #3000 grit whetstone is classified as which tier?", "answer": "Fine #3000–#5000", "options": ["Fine #3000–#5000", "Coarse #120–#400", "Medium #800–#2000", "Ultra Fine #10000+"] },
    { "scenario": "A #12000 grit whetstone is classified as which tier?", "answer": "Ultra Fine #10000+", "options": ["Ultra Fine #10000+", "Medium #800–#2000", "Fine #3000–#5000", "Coarse #120–#400"] },
    { "scenario": "You want to thin the blade behind the edge (heavy metal removal). Which grit?", "answer": "Coarse #120–#400", "options": ["Coarse #120–#400", "Fine #3000–#5000", "Very Fine #6000–#8000", "Ultra Fine #10000+"] },
    { "scenario": "In a three-stone progression, which grit typically comes right after #1000?", "answer": "Fine #3000–#5000", "options": ["Fine #3000–#5000", "Coarse #120–#400", "Ultra Fine #10000+", "Medium #800–#2000"] },
    { "scenario": "Which grit is the final polishing stone before stropping a razor edge?", "answer": "Ultra Fine #10000+", "options": ["Ultra Fine #10000+", "Coarse #120–#400", "Medium #800–#2000", "Fine #3000–#5000"] },
    { "scenario": "You want the highest possible sharpness on a single-bevel sashimi knife. Which grit?", "answer": "Ultra Fine #10000+", "options": ["Ultra Fine #10000+", "Coarse #120–#400", "Medium #800–#2000", "Very Fine #6000–#8000"] },
    { "scenario": "Which grit is the RIGHT first stone for a knife that is badly nicked?", "answer": "Coarse #120–#400", "options": ["Coarse #120–#400", "Medium #800–#2000", "Fine #3000–#5000", "Ultra Fine #10000+"] },
    { "scenario": "Your gyuto just feels a little dull and cuts undamaged tomatoes poorly. Which grit?", "answer": "Medium #800–#2000", "options": ["Medium #800–#2000", "Coarse #120–#400", "Very Fine #6000–#8000", "Ultra Fine #10000+"] },
    { "scenario": "Between coarse repair and fine polishing, which tier does the core sharpening?", "answer": "Medium #800–#2000", "options": ["Medium #800–#2000", "Coarse #120–#400", "Fine #3000–#5000", "Ultra Fine #10000+"] },
    { "scenario": "You want to remove a burr on a stone before moving to a strop. Which grit?", "answer": "Very Fine #6000–#8000", "options": ["Very Fine #6000–#8000", "Coarse #120–#400", "Medium #800–#2000", "Fine #3000–#5000"] },
    { "scenario": "Which grit range is measured with the LOWEST numbers?", "answer": "Coarse #120–#400", "options": ["Coarse #120–#400", "Medium #800–#2000", "Very Fine #6000–#8000", "Ultra Fine #10000+"] },
    { "scenario": "Which grit range is measured with the HIGHEST numbers?", "answer": "Ultra Fine #10000+", "options": ["Ultra Fine #10000+", "Coarse #120–#400", "Medium #800–#2000", "Fine #3000–#5000"] },
    { "scenario": "What is a leather strop mainly used for after sharpening?", "answer": "Remove the burr & refine the edge", "options": ["Remove the burr & refine the edge", "Reprofile a chipped bevel", "Set a brand-new edge", "Thin the blade heavily"] },
    { "scenario": "Which direction should you move the blade on a strop?", "answer": "Away from the edge (spine leading)", "options": ["Away from the edge (spine leading)", "Into the edge (edge leading)", "Straight down onto it", "Twisting side to side"] },
    { "scenario": "Common green stropping compound is made from what abrasive?", "answer": "Chromium oxide (~0.5 micron)", "options": ["Chromium oxide (~0.5 micron)", "Coarse silicon carbide", "Table salt", "Baking soda"] },
    { "scenario": "What is the main purpose of stropping between sharpenings?", "answer": "Realign & polish the edge", "options": ["Realign & polish the edge", "Repair chips", "Reprofile the bevel", "Remove rust pits"] },
    { "scenario": "A leather strop loaded with fine compound is roughly equivalent to which grit?", "answer": "Ultra-high grit (#30000+)", "options": ["Ultra-high grit (#30000+)", "Coarse #220", "Medium #1000", "Fine #3000"] },
    { "scenario": "Stropping in the wrong direction risks what?", "answer": "Cutting the leather & rolling the edge", "options": ["Cutting the leather & rolling the edge", "Over-sharpening instantly", "Nothing at all", "Rusting the blade"] },
    { "scenario": "For very hard Japanese steel, a firmer strop base is preferred. Which?", "answer": "Balsa or hard leather", "options": ["Balsa or hard leather", "Thick soft foam", "Wet sponge", "Bare glass"] },
    { "scenario": "What does stropping do to the metal of the edge?", "answer": "Deburrs & polishes with minimal removal", "options": ["Deburrs & polishes with minimal removal", "Removes lots of steel fast", "Reprofiles the whole bevel", "Adds a new coarse tooth"] },
    { "scenario": "A bare strop with no compound is used mainly to do what?", "answer": "Final polish & realign the edge", "options": ["Final polish & realign the edge", "Set a fresh bevel", "Repair a chip", "Thin the blade"] },
    { "scenario": "How often should you strop a knife you use daily?", "answer": "Often — a few passes as needed", "options": ["Often — a few passes as needed", "Only once a year", "Never", "Only after chipping it"] },
    { "scenario": "What is a typical sharpening angle PER SIDE for a double-bevel gyuto?", "answer": "About 15° per side", "options": ["About 15° per side", "About 45° per side", "About 5° per side", "About 60° per side"] },
    { "scenario": "How is a single-bevel knife like a yanagiba primarily sharpened?", "answer": "Mostly on the bevel side, with a light back touch", "options": ["Mostly on the bevel side, with a light back touch", "Equally on both sides at 20°", "Only on the flat back", "By stropping alone"] },
    { "scenario": "What tool keeps your whetstone flat over time?", "answer": "A flattening / lapping plate", "options": ["A flattening / lapping plate", "A honing steel", "A leather strop", "A ceramic mug"] },
    { "scenario": "What is a nagura stone used for?", "answer": "Raise slurry & clean the stone", "options": ["Raise slurry & clean the stone", "Repair a chipped edge", "Store the knife", "Oil the blade"] },
    { "scenario": "High-grit finishing whetstones should generally be treated how before use?", "answer": "Only splashed with water, not soaked", "options": ["Only splashed with water, not soaked", "Soaked overnight", "Baked dry", "Coated in oil"] },
    { "scenario": "A typical #1000 soaking whetstone should be prepared how?", "answer": "Soaked about 5–10 minutes first", "options": ["Soaked about 5–10 minutes first", "Used bone dry", "Frozen first", "Wiped with oil"] },
    { "scenario": "Your whetstone has become dished (concave). What should you do?", "answer": "Flatten it before sharpening", "options": ["Flatten it before sharpening", "Sharpen anyway", "Throw it away", "Soak it longer"] },
    { "scenario": "How do you check that you've raised a burr while sharpening?", "answer": "Feel the opposite side for a tiny raised edge", "options": ["Feel the opposite side for a tiny raised edge", "Weigh the knife", "Smell the steel", "Listen for a bell tone"] },
    { "scenario": "A quick, common way to test edge sharpness is to do what?", "answer": "Slice cleanly through paper", "options": ["Slice cleanly through paper", "Cut a steel bolt", "Scrape a stone", "Tap it on glass"] },
    { "scenario": "For very hard Japanese steel, which is safer for edge upkeep?", "answer": "Whetstones or a strop", "options": ["Whetstones or a strop", "A grooved steel honing rod", "A grinder wheel", "A ceramic plate bottom"] },
    { "scenario": "On a single-bevel knife, the 'uraoshi' refers to what?", "answer": "The flat back you lightly maintain", "options": ["The flat back you lightly maintain", "The handle rivet", "The wooden saya", "The coarse repair stone"] },
    { "scenario": "After sharpening a carbon-steel knife, you should do what?", "answer": "Dry it and apply a light oil", "options": ["Dry it and apply a light oil", "Leave it wet to air dry", "Soak it in water", "Put it in the dishwasher"] },
    { "scenario": "How should you wash a fine Japanese knife?", "answer": "Hand wash and dry immediately", "options": ["Hand wash and dry immediately", "Run it in the dishwasher", "Soak it in the sink overnight", "Scrub with steel wool"] },
    { "scenario": "Which cutting surface is best for a Japanese knife's edge?", "answer": "Wood or soft end-grain board", "options": ["Wood or soft end-grain board", "Glass board", "Granite countertop", "Ceramic plate"] },
    { "scenario": "Which surface should you AVOID cutting on to protect the edge?", "answer": "Glass, stone, or ceramic", "options": ["Glass, stone, or ceramic", "End-grain wood", "Soft poly board", "Hinoki cutting board"] },
    { "scenario": "How do you protect a carbon-steel blade from rust in storage?", "answer": "Wipe dry and apply camellia (tsubaki) oil", "options": ["Wipe dry and apply camellia (tsubaki) oil", "Store it damp", "Wrap it in a wet cloth", "Freeze it"] },
    { "scenario": "The dark patina that forms on carbon steel is best described as what?", "answer": "Normal and mildly protective", "options": ["Normal and mildly protective", "Dangerous rust to grind off", "A sign of a fake knife", "Cutting-board dye"] },
    { "scenario": "Is a dishwasher safe for Japanese knives?", "answer": "No — it damages the edge & handle", "options": ["No — it damages the edge & handle", "Yes, on any cycle", "Yes, if you add oil", "Yes, on the top rack only"] },
    { "scenario": "What is a good way to store Japanese knives?", "answer": "In a saya, block, or magnetic strip", "options": ["In a saya, block, or magnetic strip", "Loose in a drawer with other tools", "Blade-down in the sink", "Wrapped in a wet towel"] },
    { "scenario": "You should NOT use a thin gyuto to do what?", "answer": "Chop through hard bones", "options": ["Chop through hard bones", "Slice tomatoes", "Dice onions", "Mince herbs"] },
    { "scenario": "A finer finishing stone produces what kind of edge compared to a coarse one?", "answer": "Smoother and more refined", "options": ["Smoother and more refined", "More aggressively toothy", "Weaker and softer", "Wider and blunter"] },
    { "scenario": "A coarse, toothy edge (from low grit) is best suited to what?", "answer": "Aggressive slicing of tough skins", "options": ["Aggressive slicing of tough skins", "Mirror-polished sashimi", "Delicate garnish carving", "Push-cutting soft tofu"] },
    { "scenario": "Why raise a slurry on a finishing stone?", "answer": "It speeds polishing and refines the edge", "options": ["It speeds polishing and refines the edge", "It repairs chips", "It sets a coarse tooth", "It flattens the knife"] },
    { "scenario": "In a full sharpening workflow, which comes LAST?", "answer": "Stropping", "options": ["Stropping", "Coarse reprofiling", "Medium sharpening", "Raising the burr"] },
    { "scenario": "In a full sharpening workflow, which comes FIRST on a damaged edge?", "answer": "Coarse reprofiling", "options": ["Coarse reprofiling", "Stropping", "Ultra-fine polishing", "Oiling the blade"] },
    { "scenario": "What does a honing rod / steel actually do to an edge?", "answer": "Realigns it — it doesn't really sharpen", "options": ["Realigns it — it doesn't really sharpen", "Removes deep chips", "Reprofiles the bevel", "Polishes to a mirror"] }
  ]
};
